project:
  type: website
  output-dir: docs

website:
  title: "Shiguang WU"
  navbar:
    right:
      - blog.qmd
      - diary.qmd
      - icon: github
        href: https://github.com/Furyton
      - icon: twitter
        href: https://twitter.com/shiguang_wu
  google-analytics: "G-2J6LH2FX5K"
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css

execute:
  freeze: auto

